sudo: false

branches:
  only:
    - master

env:
  global:
  - VERSION="0.11.0"

before_check:
  - curl -fSL "https://releases.hashicorp.com/terraform/${VERSION}/terraform_${VERSION}_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - terraform version
check:
  - terraform fmt -check=true -diff=true
  - if [ $? -ne 3 ]; then
      echo "ERROR:failed to pass terraform fmt"
      exit 1
    fi 

notifications:
  email: false
