sudo: false

branches:
  only:
  - master

env:
  global:
  - VERSION="0.11.0"

before_script:
  - curl -fSL "https://releases.hashicorp.com/terraform/${VERSION}/terraform_${VERSION}_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - terraform version

script:
  - terraform fmt -check=true -diff=true

notifications:
  email: false

#  vim: set ts=2 sw=2 tw=0 et:
