sudo: false

branches:
  only:
    - master

env:
  global:
  - VERSION="0.11.0"

before_script:
  - curl -fSL "https://releases.hashicorp.com/terraform/${VERSION}/terraform_${VERSION}_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - terraform version
script:
  - ./test/check-fmt.sh

notifications:
  email: false
